export const HEADER_HEIGHT = 60
export const HEADER_HEIGHT_MOBILE = 45
export const NAVBAR_HEIGHT = 41
export const NAVBAR_HEIGHT_MOBILE = 36
export const SAFE_TOP_HEIGHT = HEADER_HEIGHT + NAVBAR_HEIGHT
export const SAFE_TOP_HEIGHT_MOBILE = HEADER_HEIGHT_MOBILE + NAVBAR_HEIGHT_MOBILE
export const TESTIMONIAL_IMAGE_SIZE = 238
export const CONTENT_PADDING = 60

export const ZINDEX_LOADINGBAR = 30
export const ZINDEX_HEADER = 20
export const ZINDEX_NAVBAR = 19
export const ZINDEX_CONTENT = 15
export const ZINDEX_FOOTER = 11
export const ZINDEX_SIDEBAR = 10
export const ZINDEX_FRAME_TOGGLE = 1

export const SUPPORTED_TOKEN_TYPES = ['EMAIL_TOKEN', 'APP']
