const ENV =
  typeof window !== 'undefined'
    ? window.__NEXT_DATA__.env
    : process.env

export const LOCALE = ENV.LOCALE
export const API_URL = ENV.API_URL
export const API_WS_URL = ENV.API_WS_URL
export const API_AUTHORIZATION_HEADER = ENV.API_AUTHORIZATION_HEADER

export const PUBLIC_BASE_URL = ENV.PUBLIC_BASE_URL
export const STATIC_BASE_URL = ENV.STATIC_BASE_URL || ENV.PUBLIC_BASE_URL

export const PIWIK_URL_BASE = ENV.PIWIK_URL_BASE
export const PIWIK_SITE_ID = ENV.PIWIK_SITE_ID

export const SG_COLORS = ENV.SG_COLORS
export const SG_FONT_FAMILIES = ENV.SG_FONT_FAMILIES
export const SG_FONT_FACES = ENV.SG_FONT_FACES
export const SG_LOGO_PATH = ENV.SG_LOGO_PATH
export const SG_LOGO_VIEWBOX = ENV.SG_LOGO_VIEWBOX
export const SG_BRAND_MARK_PATH = ENV.SG_BRAND_MARK_PATH
export const SG_BRAND_MARK_VIEWBOX = ENV.SG_BRAND_MARK_VIEWBOX

export const CROWDFUNDING_NAME = ENV.CROWDFUNDING_NAME

export const STRIPE_PUBLISHABLE_KEY = ENV.STRIPE_PUBLISHABLE_KEY
export const PF_PSPID = ENV.PF_PSPID
export const PF_FORM_ACTION = ENV.PF_FORM_ACTION
export const PAYPAL_FORM_ACTION = ENV.PAYPAL_FORM_ACTION
export const PAYPAL_BUSINESS = ENV.PAYPAL_BUSINESS
export const PAYPAL_DONATE_LINK = ENV.PAYPAL_DONATE_LINK

export const EMAIL_CONTACT = ENV.EMAIL_CONTACT
export const EMAIL_IR = ENV.EMAIL_IR
export const EMAIL_PAYMENT = ENV.EMAIL_PAYMENT
