const ENV =
  typeof window !== 'undefined' ? window.__NEXT_DATA__.env : process.env

export const LOCALE = ENV.LOCALE
export const API_URL = ENV.API_URL
export const API_WS_URL = ENV.API_WS_URL
export const API_ASSETS_BASE_URL = ENV.API_ASSETS_BASE_URL
export const ASSETS_SERVER_BASE_URL = ENV.ASSETS_SERVER_BASE_URL
export const API_AUTHORIZATION_HEADER = ENV.API_AUTHORIZATION_HEADER

export const APP_OPTIONS =
  !!ENV.APP_OPTIONS && ENV.APP_OPTIONS !== 'false' && ENV.APP_OPTIONS !== '0'

export const PUBLIC_BASE_URL = ENV.PUBLIC_BASE_URL
export const CDN_FRONTEND_BASE_URL =
  ENV.CDN_FRONTEND_BASE_URL || ENV.PUBLIC_BASE_URL
export const RENDER_FRONTEND_BASE_URL =
  ENV.RENDER_FRONTEND_BASE_URL || PUBLIC_BASE_URL

export const PUBLIKATOR_BASE_URL = ENV.PUBLIKATOR_BASE_URL
export const ADMIN_BASE_URL = ENV.ADMIN_BASE_URL

export const PIWIK_URL_BASE = ENV.PIWIK_URL_BASE
export const PIWIK_SITE_ID = ENV.PIWIK_SITE_ID

export const SG_COLORS = ENV.SG_COLORS
export const SG_FONT_STYLES = ENV.SG_FONT_STYLES
export const SG_FONT_FACES = ENV.SG_FONT_FACES
export const SG_LOGO_PATH = ENV.SG_LOGO_PATH
export const SG_LOGO_VIEWBOX = ENV.SG_LOGO_VIEWBOX
export const SG_LOGO_GRADIENT = ENV.SG_LOGO_GRADIENT
export const SG_BRAND_MARK_PATH = ENV.SG_BRAND_MARK_PATH
export const SG_BRAND_MARK_VIEWBOX = ENV.SG_BRAND_MARK_VIEWBOX
export const SG_DYNAMIC_COMPONENT_BASE_URLS = ENV.SG_DYNAMIC_COMPONENT_BASE_URLS

export const CROWDFUNDING = ENV.CROWDFUNDING
export const CROWDFUNDING_PLEDGE = ENV.CROWDFUNDING_PLEDGE || CROWDFUNDING
export const CROWDFUNDING_META = ENV.CROWDFUNDING_META || CROWDFUNDING

export const STRIPE_PUBLISHABLE_KEY = ENV.STRIPE_PUBLISHABLE_KEY
export const STRIPE_PUBLISHABLE_KEY_CONNECTED =
  ENV.STRIPE_PUBLISHABLE_KEY_CONNECTED
export const PF_PSPID = ENV.PF_PSPID
export const PF_FORM_ACTION = ENV.PF_FORM_ACTION
export const PAYPAL_FORM_ACTION = ENV.PAYPAL_FORM_ACTION
export const PAYPAL_BUSINESS = ENV.PAYPAL_BUSINESS
export const PAYPAL_DONATE_LINK = ENV.PAYPAL_DONATE_LINK

export const EMAIL_CONTACT = ENV.EMAIL_CONTACT
export const EMAIL_IR = ENV.EMAIL_IR
export const EMAIL_PAYMENT = ENV.EMAIL_PAYMENT || ENV.EMAIL_CONTACT

export const CURTAIN_MESSAGE = ENV.CURTAIN_MESSAGE
export const CURTAIN_META = ENV.CURTAIN_META
export const CURTAIN_COLORS = ENV.CURTAIN_COLORS

export const DISCUSSION_POLL_INTERVAL_MS = +ENV.DISCUSSION_POLL_INTERVAL_MS || 0
export const STATS_POLL_INTERVAL_MS = +ENV.STATS_POLL_INTERVAL_MS || 0
export const STATUS_POLL_INTERVAL_MS = +ENV.STATUS_POLL_INTERVAL_MS || 0

export const ELECTION_COOP_MEMBERS_SLUG = ENV.ELECTION_COOP_MEMBERS_SLUG
export const ELECTION_COOP_PRESIDENT_SLUG = ENV.ELECTION_COOP_PRESIDENT_SLUG
export const VOTING_COOP_ACCOUNTS_SLUG = ENV.VOTING_COOP_ACCOUNTS_SLUG
export const VOTING_COOP_DISCHARGE_SLUG = ENV.VOTING_COOP_DISCHARGE_SLUG
export const VOTING_COOP_BUDGET_SLUG = ENV.VOTING_COOP_BUDGET_SLUG
export const VOTING_COOP_BOARD_SLUG = ENV.VOTING_COOP_BOARD_SLUG

export const GENERAL_FEEDBACK_DISCUSSION_ID = ENV.GENERAL_FEEDBACK_DISCUSSION_ID
export const PROGRESS_EXPLAINER_PATH = ENV.PROGRESS_EXPLAINER_PATH

export const ONBOARDING_PACKAGES = ['ABO', 'BENEFACTOR', 'MONTHLY_ABO']

export const TRIAL_CAMPAIGN = ENV.TRIAL_CAMPAIGN
export const TRIAL_CAMPAIGNS = ENV.TRIAL_CAMPAIGNS

export const ONBOARDING_SECTIONS_REPO_IDS = ENV.ONBOARDING_SECTIONS_REPO_IDS
