const nextRoutes = require('next-routes')
const routes = nextRoutes()

routes
  .add('index', '/')
  .add('account', '/account')
  .add('profile', '/~:slug')
  .add('discussions', '/discussions')
  .add('discussion', '/discussion')
  .add('events', '/events/:slug?')
  .add('faq', '/faq')
  .add('feed', '/feed')
  .add('community', '/community')
  .add('crew', '/crew')
  .add('en', '/en')
  .add('manifest', '/manifest')
  .add('media', '/media')
  .add('pledge', '/pledge')
  .add('claim', '/claim')
  .add('updates', '/updates/:slug?')
  .add('notifications', '/notifications')
  .add('legal/imprint', '/legal/imprint')
  .add('legal/privacy', '/legal/privacy')
  .add('legal/statute', '/legal/statute')
  .add('legal/tos', '/legal/tos')
  .add('article', '/:year(\\d{4})/:month(\\d{2})/:day(\\d{2})/:slug')

module.exports = routes
