const nextRoutes = require('next-routes')
const routes = nextRoutes()

routes
  .add('index', '/')
  .add('signin', '/anmelden')
  .add('account', '/konto')
  .add('profile', '/~:slug')
  .add('discussion', '/diskussion')
  .add('events', '/veranstaltungen')
  .add('event', '/veranstaltung/:slug', 'events')
  .add('faq', '/faq')
  .add('feed', '/feed')
  .add('community', '/community')
  .add('crew', '/crew')
  .add('en', '/en')
  .add('manifest', '/manifest')
  .add('media', '/medien')
  .add('pledge', '/angebote')
  .add('claim', '/abholen')
  .add('updates', '/updates/:slug?')
  .add('notifications', '/mitteilung')
  .add('legal/imprint', '/impressum')
  .add('legal/privacy', '/datenschutz')
  .add('legal/statute', '/statuten')
  .add('legal/tos', '/agb')
  .add('format', '/format/:slug', 'article')
  .add('dossier', '/dossier/:slug', 'article')
  .add('article', '/:year(\\d{4})/:month(\\d{2})/:day(\\d{2})/:slug/:suffix(diskussion)?')

module.exports = routes
